name: 'Proselint correctur'

on:
  push:
     branches: 
       -  main 
  pull_request:
     branches:
       -  main

jobs:
  build:
    steps:
      - uses: actions/checkout@v2
      - name: Run proselint script
        run: sh ./parse.sh
